import img1101 from '../../assets/recent/img1101.png'
import img1201 from '../../assets/recent/img1201.png'
import img1301 from '../../assets/recent/img1301.png'
import img1401 from '../../assets/recent/img1401.png'
import img1501 from '../../assets/recent/img1501.png'
import img1601 from '../../assets/recent/img1601.png'

import img2101 from '../../assets/health/img1101.png'
import img2201 from '../../assets/health/img1201.png'
import img2301 from '../../assets/health/img1301.png'

import img3101 from '../../assets/science/1301.png'
import img3201 from '../../assets/science/1302.png'
import img3301 from '../../assets/science/1303.png'



export const recent = [
    {
        img: img1101,
        title: 'GREAT PLEA system proposed for responsible use of generative AI in healthcare',
        content: 'In a recent study published in the journal NPJ Digital Medicine, researchers reviewed current guidelines on the ethical implementation of Artificial Intelligence (AI) in military and healthcare applications. Their discussions focus on ‘generative AI,’ a novel technology aimed at efficiently generating information, and attempts to overcome currently prevalent limitations on the ethical use of the technology. They develop and propose a novel system for the ethical application of AI to military and clinical research, named the “GREAT PLEA.”',
        head1: 'AI and the need for ethics',
        headCont1: 'Artificial Intelligence (AI) is the simulation of human intelligence processes by machines, especially computer systems. With the increasing computational power of modern hardware and the widespread adoption of smart devices, access to and the adoption of AI is higher than ever. AI has percolated into and revolutionized almost every aspect of modern human society, with machine learning tools seeing widespread utilization in online advertisements, scientific research, and military simulations. The military sector particularly benefits from AI tools, with the ongoing conflicts between Russia and Ukraine expected to pave the way for autonomous AI-guided weapon systems. Unfortunately, the development of AI tools is rarely accompanied by an ethical evaluation of the system, with collateral damages to non-combatants or friend forces left unconsidered.'
    },
    {
        img:img1201,
        title:'Irregular sleep patterns linked to cognitive decline in older adults, study shows',
        content:'In a recent study published in the journal JAMA Network Open, researchers evaluated the association between sleep patterns and age-associated cognitive alterations among older adults.',
        head1: 'About the study',
        headContent1: 'In the present study, researchers investigated whether longitudinal patterns of self-documented sleep duration were associated with cognitive impairment among older adults. The team longitudinally analyzed the Seattle Longitudinal Study (SLS) data; the study assessed cognitive function (between 1997 and 2020) and self-documented sleep durations (between 1993 and 2012) among older adults. The team enrolled SLS participants from the Health Maintenance Organization (HMO) of Washington and the Group Health Cooperative (GHC) of Puget Sound from 1956 to 2020. The researchers included only individuals who provided complete demographic data and those who were administered the neuropsychologic battery and filled out the Health Behavior Questionnaire (HBQ). Self-reported demographic data included sex (male or female), ethnicity, race, apolipoprotein E ε4 (APOE*E4) allele carrier status, and educational attainment. The participants filled out the HBQ every three to five years, five times from 1993 to 2012, and underwent neuropsychological assessments every five to seven years from 1997 to 2019. Cognitive impairment was the study outcome, as described by performances below thresholds on the Mattis Dementia Rating Scale (DRS, scores below 129) and the Mini-Mental State Examination (MMSE, scores below 26). In addition, the SLS neuropsychological battery included the Center for Epidemiologic Studies-Depression Scale (CES-D). Sleep duration was self-reported as the median of night sleep over the previous week and evaluated longitudinally at several time points. The researchers evaluated sleep phenotypes [short sleep (less than seven hours), medium sleep (seven hours), long sleep (more than seven hours)], median duration of sleep, sleep duration alterations, and sleep variability. They performed Cox proportional-type hazard regression modeling to determine the hazard ratios (HRs) and data analysis between September 2020 and May 2023.'
    },
    {
        img: img1301,
        title: 'Sympathetic nervous system and immune interplay: Key to metabolic regulation', 
        content: 'In a review published in the journal Advanced Science, researchers discussed the interplay of the immune system and the sympathetic regulation of vital metabolic organs such as the pancreas, intestine, liver, and adipose tissues. Insights from the review help improve our understanding of metabolic regulation of organs and pave the way for new therapeutic strategies against metabolic diseases.',
        head1: 'Sympathetic-immune landscape in the pancreas',
        headContent1: 'The pancreas plays a vital role in the endocrine and exocrine functions of the body. While the nervous systems role in regulating the pancreas is established, increasing evidence suggests additional immune system involvement. The pancreas gets sympathetic innervation from the thoracic and upper lumbar spinal cord segments. The sympathetic control, mediated by norepinephrine (NE), influences blood vessels, pancreatic islets, and exocrine acinar cells. Sympathetic stimulation typically increases blood glucose through elevated glucagon, reduced insulin secretion, and decreased blood flow, while sympathetic inhibition has the opposite effect. Additionally, sensory afferent innervation contributes to the overall activity, ensuring proper pancreatic function and glucose metabolism. Sympathetic innervation in pancreatic islets influences immune modulation, playing a crucial role in protecting against autoimmune diabetes. In type 1 diabetes (T1D), sympathetic nerve loss is observed, impacting the autoimmune response. Inhibiting sympathetic innervation or α1-adrenergic receptor blockade effectively halts the autoimmune response. Pancreatic islets harbor resident macrophages displaying a pro-inflammatory state, contributing to inflammation and sympathetic nerve damage. Targeting adrenergic receptors on immune cells reduces pro-inflammatory cytokines, preserves β-cell function, and mitigates T1D development in mice.'
    },
    {
        img: img1401,
        title: 'New genetic links to coronary artery calcification uncovered, offering treatment insights', 
        content: 'A recent research letter published in the journal Nature Cardiovascular Research describes two new genetic loci associated with coronary artery calcification (CAC). CAC is a measure of atherosclerosis and predicts coronary artery disease (CAD) events. Coronary calcification is a manifestation of atherosclerotic plaque. It is suggested to contribute to plaque rupture when present as microcalcifications, while more extensive calcification sheets are associated with stabilizing the plaque.',
        head1: 'The study and findings',
        headContent1: 'In the present study, researchers performed a GWAS to identify CAC loci. Around 22,400 individuals from 10 studies, with whole-genome sequencing and CAC data, were included and stratified based on race/ethnicity. Participants were an average age of 58, 53% male and 47% female. Half the population had detectable CAC. In single-variant analyses, over 28.5 million variants with minor allele count ≥ 50 were tested for associations with CAC. Genetic variants showing a significant association with CAC were detected at six loci – 9p21, matrix metallopeptidase 16 (MMP16), apolipoprotein B (APOB), APOE, arylsulfatase E (ARSE), and phosphatase and actin regulator 1/endothelin 1 (PHACTR1/EDN1). Next, rare variants (minor allele frequency < 1%) were tested for associations with CAC using gene-based variant aggregation and filtering. This resulted in a genome-wide significant aggregation unit for CAC mapping to APOB. However, the associations were insignificant when adjusted for the index variant identified at that locus in the single-variant analysis. Genetic variants in MMP16 and ARSE were not previously reported to be associated with CAD or CAC at a genome-wide significance level. The inverse association between CAC and the G allele of the ARSE index variant (rs5982944) followed a recessive mode of inheritance. Further, the index variant at ARSE was associated with carotid plaque, low- (LDL-C) and high-density lipoprotein cholesterol (HDL-C), and systolic blood pressure. It was also associated with thoracic ascending and descending aorta calcification. On the other hand, the MMP16 index variant (rs13268080) showed nominal associations with CAD events and was not significantly associated with any other atherosclerotic phenotypes.'
    },
    {
        img: img1501,
        title: 'Mediterranean diet linked to improved sperm quality',
        content: 'A recent study in the journal Nutrients evaluates whether adherence to the Mediterranean diet (MD) affects sperm parameters.',
        head1: 'About the study',
        headContent1: 'The current study hypothesized that higher MD adherence would positively benefit male reproductive health and sperm parameters. The present observational cross-sectional study evaluated the association between MD adherence and sperm parameters. Individuals who were referred to the Andrology and Reproductive Medicine Unit, University Hospital of Padova, between September 2022 and July 2023 for semen analysis were considered for this study. All participants were between 18 and 45 years of age and did not have a history of varicocele, testicular cancer, endocrinopathies, genetic causes of infertility, and semen infections. Semen samples were collected from participants after two to seven days of sexual abstinence and were analyzed. The body mass index (BMI) of all participants selected in this study was estimated. Adherence to MD was assessed using a validated 14-point a priori Mediterranean Diet Adherence Screener (MEDAS) in the presence of a dietitian.'
    },
    {
        img: img1601,
        title: 'Study challenges link between proton pump inhibitors and kidney disease risk',
        content: 'A recent Scientific Reports study investigates whether the association between proton pump inhibitors (PPIs) and the use of histamine-2 receptor antagonists (H2RA) affects the risk of chronic kidney disease (CKD).',
        head1: 'About the study',
        headContent1: 'A total of 1,125,700 participants were included in the NHIS-NSC CDM database between 2002 and 2013, whereas the six-hospital CDM databases offered more extensive data, comprising 10,083,608 subjects between 1999 and 2018. To control for potential confounding factors and balance the baseline characteristics between PPI and H2RA groups, large-scale propensity score matching (PSM) was performed. Based on eligibility, 5,967 participants were selected for both groups. PPI use was not associated with an increased risk of CKD compared to H2RAs. Although previous studies have indicated an association between PPI use and the incidence of CKD, the mechanism responsible for this association remained elusive. It is possible that unclear mechanisms and contradictory observational studies resulted in the link between long-term PPI use and CKD. In addition, these studies failed to determine the duration and quantity of PPI use that increased the risk of developing CKD.'
    }


];

export const healths = [
    {
        img: img2101,
        title: 'Healthcare Supply Chain Resilience: Lessons Learned from the Pandemic and Strategies for the Future',
        content: 'The coronavirus disease 2019 (COVID-19) pandemic significantly altered how many industries worked, not least the global healthcare industry. In particular, healthcare supply chains were drastically impacted by the pandemic. Healthcare supply chains have not returned to their previous operations; it seems they have been forever changed.',
        head1: 'The pre-pandemic supply chain',
        headContent1: 'Before the COVID-19 pandemic hit, the operations of healthcare supply chains focussed on cost-effectiveness, efficiency, and most often worked on a just-in-time method of inventory management. Below, we discuss some of the key features of healthcare supply chains in the pre-pandemic era. The just-in-time strategy involves moving supplies just before they are needed. If needs are anticipated accurately, then this method allows little inventory to be stocked, which can reduce storage costs. The just-in-time approach goes hand-in-hand with the lean inventory management approach. This is where stockpiling is reduced to as minimal as possible; the aim here is to strike the perfect balance between supply and demand, reducing the overheads of keeping stock while being able to respond to demand without incurring long wait times. Before the pandemic, healthcare supply chains very often used these lean, just-in-time approaches. In addition, in the pre-pandemic era, healthcare supply chains were often globalized, meaning that medicines and devices were sourced from across the globe - the assumption being that access to these supplies is rapid and simple given global travel. The COVID-19 pandemic rapidly highlighted vulnerabilities in the healthcare supply chain. With the breakdown of global logistics, supply chains rapidly broke down. The just-in-time approach could not work in a world where international supplies were no longer accessible. Lean inventories were wiped out as demand rapidly exceeded supply.'
    },
    {
        img:img2201,
        title: 'Digital Nutrition: How Social Media Consumption Affects Our Mental Diet',
        content: 'The term “Digital Nutrition” was coined by a Sydney-based psychologist, Jocelyn Brewer, to describe the impact of social media habits on our mental wellbeing and provide guidance on developing healthy digital habits and improving our digital wellbeing. “Digital Nutrition” is a guilt-free philosophy to guide the intentional and intelligent use of digital platforms and the conscious consumption of digital content.',
        head1: 'How may social media habits impact mental wellbeing?',
        headContent1: 'Studies investigating the effect of social media use on mental wellbeing have produced mixed results. While some studies have clearly mentioned potential detrimental health effects of digital platforms, some have highlighted its positive effects. Mental health consequences of social media use mostly depend on the type of content and the time spent on various social media platforms. An experience of cyberbullying or an exposure to violent, sexual, and hateful content can certainly have serious negative mental health impacts, especially among children, adolescents, and young adults. In contrast, social and emotional connections developed through online platforms can potentially boost the mental health of minority communities who often experience health disparities and chronic health conditions. A growing-pool of evidence indicates that people who intend to compare themselves with digitally-enhanced images online, or compare their social media popularity with others are more likely to experience negative mental health consequences, such as anxiety and depression. Similarly, social media use has been found to trigger body image concerns and increase the risk of deadly psychiatric illnesses, such as eating disorders. In contrast, it has been observed that certain positive social media experiences, such as having an online conversation with someone during lonely hours or making healthy social networks, are associated with happiness, meaning and purpose, physical and mental health, character, close social relationships, and financial stability.    '
    },
    {
        img:img2301, 
        title: 'What is Lymphangioleiomyomatosis (LAM)?',
        content: 'A rare neoplastic condition, lymphangioleiomyomatosis or LAM, is associated with abnormalities in the lungs and kidneys. It is a multisystemic disease linked with TSC1 (tuberous sclerosis complex) and TSC2 mutations commonly observed in young women. LAM patients exhibit a range of clinical symptoms, including cystic lung lesions, dyspnea, and recurrent pneumothorax.',
        head1: 'Causes and pathophysiology',  
        headContent1: 'Two different forms of lymphangioleiomyomatosis- sporadic and inherited- have been described in the literature. Sporadic LAM is associated with mutations in the TSC2 genes, while the inherited form may occur due to mutations in the TSC1 and TSC2 genes. These tuberous sclerosis complex genes are responsible for the production of proteins (hamartin and tuberin) that inhibit the target of the mTOR (mechanistic target of rapamycin) signaling pathway. This pathway plays a crucial role in regulating the size and proliferation of cells. It is a progressive chronic condition, categorized as a low-grade metastasizing lung neoplasm by the World Health Organization (WHO). The abnormal hyperplastic smooth muscle cells that proliferate around and along lymphatic channels, blocking lymphatics, veins, and airways, are the pathogenic hallmarks of LAM. Neoplastic smooth muscle-like cells, or LAM cells, proliferate in minute clusters at the margins of cysts as well as along blood arteries, lymphatics, and bronchioles in lung lesions. Venous occlusion and bleeding, vascular wall thickening, disruption of the lymphatic arteries, and obstruction of the airways are brought on by LAM cell infiltrates.'
    }
];

export const science = [
    {
        img:img3101,
        title: 'Revolutionizing Proteomics: Unlocking the potential of automation to overcome industry bottlenecks',
        content: 'Proteomics is the area of research that studies protein expression, interactions, function, structure, and post-translational modifications. It can detect and quantify all the modifications and complex interactions of the proteins within a sample, which means this technique holds great potential for identifying therapeutic biomarkers for drug development as well as targeted treatment with precision medicine. This prospect is backed by significant financial investment—the global proteomics market is expected to grow by 14.6% and reach $72.9 billion in total market revenue over the next five years.',
        head1: 'Prevalence of manual workflows',
        headContent1: 'Recent advances in liquid chromatography-tandem mass spectrometry (LC-MS) have enabled scientists and clinicians to analyze thousands of protein markers in a single sample. However, the quality of the LC-MS analysis hinges on the sample preparation stage, a critical juncture that affects the accuracy, reproducibility, and throughput of the results. This is because sample preparation workflows in proteomics are still highly manual and time-consuming, making the process prone to human errors. To ensure successful runs, technicians must be highly skilled and trained to perform specialized procedures such as cell lysis, protein extraction and separation, reduction and alkylation, digestion, and peptide assays on many samples. Each of these techniques is repetitive and meticulous, involving many manual pipetting steps and requiring significant sorting and tracking of samples through each experiment.'
    },
    {
        img:img3201,
        title: 'The Power of Process Analytical Technology (PAT) in Pharmaceutical Manufacturing',
        content: 'Technological innovations throughout the past several decades have transformed the pharmaceutical manufacturing process from traditional batch production to autonomous and continuous manufacturing.',
        head1: 'Introduction to PAT in pharmaceutical manufacturing',
        headContent1: 'According to the United States Food and Drug Administration (FDA), PAT can be further classified as multivariate tools, process analyzers, process control tools, as well as continuous improvement and knowledge management tools. Taken together, these tools allow scientists to continuously and immediately obtain data on crucial API properties without the need for offline analysis, thereby improving the efficiency of drug manufacturing, as well as the selectivity, purity, efficacy, and output of APIs. Discover Drug Discovery & Pharmaceuticals Equipment Here Spectroscopic techniques such as infrared (IR), Raman, and UV-Vis spectroscopy, chromatographic techniques, as well as particle size and mass measurement tools, can be incorporated in situ or through continuous flow systems to be considered PAT. For example, combining Raman and IR spectroscopy with advanced data analysis strategies such as machine learning and chemometric tools allows for extracting crucial information embedded within the data.'
    },
    {
        img:img3301,
        title: 'Pharmaceutical Manufacturing Evolution: Mastering Process Development and Scale-Up for Market Success',
        content: 'Process development is the exercise of creating new and improved manufacturing methods, optimizing them in terms of time and financial efficiency while maintaining regulatory compliance and product quality.',
        head1: 'Quality by Design (QbD) principles',
        headContent1: 'Quality by Design (QbD) is the idea that quality should be designed into a product from the earliest stages, avoiding potential issues with manufacture and the product life-cycle from the outset. The US Food and Drug Administration (FDA) emphasizes a risk-based approach to QbD principles in drug product process development. It recognizes that increased testing does not necessarily improve product quality. Quality must be built into the product and its manufacturing process in order to ensure a sterile and pharmaceutically effective product. QbD is therefore concerned with process development and manufacturing efficiency, particularly the elimination of defects via process understanding and control. A systematic approach relies on thorough data collection at each stage of the manufacturing process, from checking the condition of precursor compounds before use to continuous monitoring of temperature and chemical parameters within the reaction. Root cause analysis can, therefore, be performed should a batch not meet the expected quality standards from the established process, and proactive actions can be taken to prevent future reoccurrence.'
    }
];